### ISSUE TITLE
[FEATURE] add footer for social links

### ISSUE THREAD

**Issue by rufilboy** [FreeOps-Tools/LogIQ#36]
### Description

Add social media links

**Comment by sudhz** [comment]
Hi, I would like to work on adding this feature. Could you please provide all the links to your socials, so that I can add them to the footer?

**Comment by rufilboy** [comment]
Just finished working on it

**Comment by rufilboy** [comment]
@sudhz you might take a look at other issues or you can also create one in case you see any thing you can work on
