### ISSUE TITLE
Redesigning the home page

### ISSUE THREAD

**Issue by rufilboy** [FreeOps-Tools/LogIQ#6]
### Description

It'll be nice if we can redesign the website before we dive in on the real project! 😮‍💨 😤

### Screenshots

![image](https://user-images.githubusercontent.com/69714197/227808297-47356f89-a878-42a8-9a38-1f171fc4ad32.png)

### Additional information

Tech stack: React JS, CSS

**Comment by victoriaEssien** [comment]
I would love to work on this issue @rufilboy

**Comment by rufilboy** [comment]
Thanks for your interest in this project, you can start to work on it!

**Comment by victoriaEssien** [comment]
Thank you!

**Comment by rufilboy** [comment]
Don't forget to join our Discord community here: https://discord.gg/Q6cH6pr2N6

**Comment by rufilboy** [comment]
> Thank you!

Let's chat on Discord!

**Comment by victoriaEssien** [comment]
Just sent you a message
